sonar.projectKey=Gravefax_SQS-Team-11
sonar.organization=gravefax

sonar.sources=frontend/quizzard-of-oz/app,backend/app
sonar.tests=frontend/quizzard-of-oz/app,backend/tests
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/tests/**/*.py

sonar.javascript.lcov.reportPaths=frontend/quizzard-of-oz/test-results/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.python.version=3.12
